// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmsbufmmdvrahlkytwna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtc2J1Zm1tZHZyYWhsa3l0d25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NDkyNTEsImV4cCI6MjA4NTEyNTI1MX0._M_md_MKTkz5ZOl-Vyza2oSeNMT6xBSZKFb72GQCoZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});